export const topics = [
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNN9",
    name: "Web Development",
    usersCount: 531,
    scrollCount: 2127,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRR8",
    name: "Product Design",
    usersCount: 445,
    scrollCount: 1277,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86QR",
    name: "Jobs & Referrals",
    usersCount: 470,
    scrollCount: 491,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76QK",
    name: "Hiring",
    usersCount: 393,
    scrollCount: 303,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NROR",
    name: "Open Source",
    usersCount: 382,
    scrollCount: 615,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8GB",
    name: "Marketing",
    usersCount: 129,
    scrollCount: 1015,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDN79",
    name: "Writing",
    usersCount: 118,
    scrollCount: 242,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRM8",
    name: "Artificial Intelligence",
    usersCount: 335,
    scrollCount: 539,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86KR",
    name: "Side Project",
    usersCount: 366,
    scrollCount: 1189,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76DK",
    name: "Productivity",
    usersCount: 297,
    scrollCount: 907,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NRDR",
    name: "Books",
    usersCount: 183,
    scrollCount: 160,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8NB",
    name: "Freelancing",
    usersCount: 359,
    scrollCount: 172,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNQ9",
    name: "Startups",
    usersCount: 448,
    scrollCount: 674,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGR78",
    name: "Technology Trends",
    usersCount: 343,
    scrollCount: 946,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD869R",
    name: "Product Management",
    usersCount: 206,
    scrollCount: 441,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM769K",
    name: "Events",
    usersCount: 108,
    scrollCount: 273,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NRPR",
    name: "Security",
    usersCount: 93,
    scrollCount: 272,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8BB",
    name: "Software Engineering",
    usersCount: 380,
    scrollCount: 1760,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNG9",
    name: "Indie Hacking",
    usersCount: 186,
    scrollCount: 222,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRB8",
    name: "Build In Public",
    usersCount: 289,
    scrollCount: 607,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86NR",
    name: "Startup News",
    usersCount: 264,
    scrollCount: 276,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76EK",
    name: "Mobile Apps",
    usersCount: 229,
    scrollCount: 488,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ969",
    name: "AMA",
    usersCount: 43,
    scrollCount: 28,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7OMG",
    name: "Work Memes",
    usersCount: 126,
    scrollCount: 43,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8OR9",
    name: "Devops",
    usersCount: 118,
    scrollCount: 128,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLM8K",
    name: "System Design",
    usersCount: 293,
    scrollCount: 100,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89EP",
    name: "Competitive Programming",
    usersCount: 100,
    scrollCount: 50,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAER",
    name: "Finance & Investing",
    usersCount: 102,
    scrollCount: 241,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ989",
    name: "DSA",
    usersCount: 158,
    scrollCount: 48,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7OAG",
    name: "Data Science",
    usersCount: 84,
    scrollCount: 85,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8OL9",
    name: "Career Guidance",
    usersCount: 162,
    scrollCount: 338,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLMJK",
    name: "Hardware",
    usersCount: 56,
    scrollCount: 55,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89BP",
    name: "Web3",
    usersCount: 145,
    scrollCount: 47,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAGR",
    name: "Help Needed",
    usersCount: 76,
    scrollCount: 182,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ9N9",
    name: "SAAS",
    usersCount: 234,
    scrollCount: 389,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7O9G",
    name: "Developer Tools",
    usersCount: 238,
    scrollCount: 890,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8O99",
    name: "Shitposting",
    usersCount: 78,
    scrollCount: 106,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLMNK",
    name: "Sales",
    usersCount: 49,
    scrollCount: 406,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89KP",
    name: "Opinions",
    usersCount: 83,
    scrollCount: 49,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAQR",
    name: "Ask Peerlist",
    usersCount: 146,
    scrollCount: 26,
    relatedTopics: [],
  },
];
export const roles = [
  "Android Developer",
  "Web Developer",
  "Software Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "Project Manager",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Database Administrator",
  "Network Engineer",
  "Security Analyst",
  "Systems Architect",
  "Cloud Engineer",
  "Mobile Developer",
  "Blockchain Developer",
  "Game Developer",
  "IT Support Specialist",
  "Business Analyst",
  "Technical Writer",
];
export const joboptions = ["Full-time", "Part-time", "Contract", "Internship"];
export const integrations = [
  {
    id: 1,
    title: "DEV",
    image:
      "https://media.dev.to/cdn-cgi/image/quality=100/https://dev-to-uploads.s3.amazonaws.com/uploads/logos/resized_logo_UQww2soKuUsjaOGNB38o.png",
  },
  {
    id: 2,
    title: "Github",
    image:
      "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
  },
  {
    id: 3,
    title: "Youtube",
    image:
      "https://t3.ftcdn.net/jpg/07/22/13/68/240_F_722136822_VIVcS7fxKb4ippA6kRYCoLwvS0J69hpB.jpg",
  },
];
export const months = [
  { id: 1, name: "Jan" },
  { id: 2, name: "Feb" },
  { id: 3, name: "Mar" },
  { id: 4, name: "Apr" },
  { id: 5, name: "May" },
  { id: 6, name: "Jun" },
  { id: 7, name: "July" },
  { id: 8, name: "Aug" },
  { id: 9, name: "Sept" },
  { id: 10, name: "Oct" },
  { id: 11, name: "Nov" },
  { id: 12, name: "Dec" },
];
export const years = Array.from({ length: 2024 - 2000 + 1 }, (_, i) => ({
  id: 2000 + i,
  name: 2000 + i,
}));
export const degrees = [
  { id: 1, name: "Associate" },
  { id: 2, name: "Bachelor" },
  { id: 3, name: "Master" },
  { id: 4, name: "Doctorate" },
  { id: 5, name: "Professional" },
  { id: 6, name: "Certificate" },
  { id: 7, name: "Diploma" },
  { id: 8, name: "Advanced Diploma" },
  { id: 9, name: "Honours" },
  { id: 10, name: "Fellowship" },
];
